/**
 * keygen.js — Client-side random key & password generator
 * Uses crypto.getRandomValues() — no data leaves the browser.
 *
 * Part of MarkusBitterman.github.io Toolbox
 */

(function () {
  "use strict";

  // --- Character sets ---
  const CHARSETS = {
    alpha: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ",
    lower: "abcdefghijklmnopqrstuvwxyz",
    upper: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    digits: "0123456789",
    hex: "0123456789abcdef",
    symbols: "!@#$%^&*()-_=+[]{}|;:,.<>?",
    alphanum: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",
    full: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()-_=+[]{}|;:,.<>?",
  };

  // --- Core random helpers ---
  function randomBytes(n) {
    var arr = new Uint8Array(n);
    crypto.getRandomValues(arr);
    return arr;
  }

  function randomFromCharset(charset, length) {
    var result = "";
    var charsetLength = charset.length;

    // Use rejection sampling to avoid modulo bias when mapping bytes to charset indices.
    while (result.length < length) {
      // Generate enough bytes to potentially fill the remaining length.
      var bytes = randomBytes(length - result.length);
      for (var i = 0; i < bytes.length && result.length < length; i++) {
        var idx = bytes[i];
        if (idx < charsetLength) {
          result += charset[idx];
        }
      }
    }
    return result;
  }

  function randomHex(bytes) {
    var arr = randomBytes(bytes);
    var result = "";
    for (var i = 0; i < arr.length; i++) {
      result += ("0" + arr[i].toString(16)).slice(-2);
    }
    return result;
  }

  function randomBase64(bytes) {
    var arr = randomBytes(bytes);
    var binary = "";
    for (var i = 0; i < arr.length; i++) {
      binary += String.fromCharCode(arr[i]);
    }
    return btoa(binary);
  }

  // UUID v4
  function uuidV4() {
    var bytes = randomBytes(16);
    bytes[6] = (bytes[6] & 0x0f) | 0x40; // version 4
    bytes[8] = (bytes[8] & 0x3f) | 0x80; // variant 10
    var hex = "";
    for (var i = 0; i < 16; i++) {
      hex += ("0" + bytes[i].toString(16)).slice(-2);
    }
    return (
      hex.slice(0, 8) +
      "-" +
      hex.slice(8, 12) +
      "-" +
      hex.slice(12, 16) +
      "-" +
      hex.slice(16, 20) +
      "-" +
      hex.slice(20, 32)
    );
  }

  // Passphrase from a small embedded word list (BIP39-inspired subset)
  var WORDS = [
    "abandon",
    "able",
    "about",
    "above",
    "absent",
    "absorb",
    "abstract",
    "absurd",
    "abuse",
    "access",
    "accident",
    "account",
    "accuse",
    "achieve",
    "acid",
    "across",
    "act",
    "action",
    "actor",
    "actual",
    "adapt",
    "add",
    "addict",
    "address",
    "adjust",
    "admit",
    "adult",
    "advance",
    "advice",
    "aerobic",
    "affair",
    "afford",
    "afraid",
    "again",
    "age",
    "agent",
    "agree",
    "ahead",
    "aim",
    "air",
    "airport",
    "aisle",
    "alarm",
    "album",
    "alert",
    "alien",
    "allow",
    "almost",
    "alone",
    "alpha",
    "already",
    "alter",
    "always",
    "amateur",
    "amazing",
    "among",
    "amount",
    "amuse",
    "anchor",
    "ancient",
    "anger",
    "angle",
    "angry",
    "animal",
    "ankle",
    "announce",
    "annual",
    "another",
    "answer",
    "antenna",
    "antique",
    "anxiety",
    "any",
    "apart",
    "apology",
    "appear",
    "apple",
    "approve",
    "april",
    "arena",
    "argue",
    "armor",
    "army",
    "arrest",
    "arrive",
    "arrow",
    "art",
    "asset",
    "assist",
    "assume",
    "atom",
    "attack",
    "attend",
    "attract",
    "auction",
    "audit",
    "august",
    "aunt",
    "author",
    "auto",
    "avocado",
    "avoid",
    "awake",
    "aware",
    "awesome",
    "awful",
    "axis",
    "baby",
    "bachelor",
    "bacon",
    "badge",
    "bag",
    "balance",
    "balcony",
    "ball",
    "bamboo",
    "banana",
    "banner",
    "bar",
    "barely",
    "bargain",
    "barrel",
    "base",
    "basic",
    "basket",
    "battle",
    "beach",
    "bean",
    "beauty",
    "because",
    "become",
    "beef",
    "before",
    "begin",
    "behave",
    "behind",
    "believe",
    "below",
    "belt",
    "bench",
    "benefit",
    "best",
    "betray",
    "better",
    "between",
    "beyond",
    "bicycle",
    "bid",
    "bike",
    "bind",
    "biology",
    "bird",
    "birth",
    "bitter",
    "black",
    "blade",
    "blame",
    "blanket",
    "blast",
    "bleak",
    "bless",
    "blind",
    "blood",
    "blossom",
    "blow",
    "blue",
    "blur",
    "blush",
    "board",
    "boat",
    "body",
    "boil",
    "bomb",
    "bone",
    "bonus",
    "book",
    "boost",
    "border",
    "boring",
    "borrow",
    "boss",
    "bottom",
    "bounce",
    "box",
    "brain",
    "brand",
    "brave",
    "bread",
    "breeze",
    "brick",
    "bridge",
    "brief",
    "bright",
    "bring",
    "brisk",
    "broken",
    "bronze",
    "broom",
    "brother",
    "brown",
    "brush",
    "bubble",
    "buddy",
    "budget",
    "buffalo",
    "build",
    "bulb",
    "bulk",
    "bullet",
    "bundle",
    "burden",
    "burger",
    "burst",
    "busy",
    "butter",
    "buyer",
    "cabin",
    "cable",
    "cactus",
    "cage",
    "cake",
    "call",
    "calm",
    "camera",
    "camp",
    "canal",
    "cancel",
    "candy",
    "cannon",
    "canvas",
    "canyon",
    "capable",
    "capital",
    "captain",
    "carbon",
    "card",
    "cargo",
    "carpet",
    "carry",
    "cart",
    "case",
    "cash",
    "casino",
    "castle",
    "catalog",
    "catch",
    "category",
    "cattle",
    "caught",
    "cause",
    "caution",
    "cave",
    "ceiling",
    "celery",
    "cement",
    "census",
    "century",
    "cereal",
    "certain",
    "chair",
    "chalk",
    "champion",
    "change",
    "chaos",
    "chapter",
    "charge",
    "chase",
    "cheap",
    "check",
    "cheese",
    "cherry",
    "chest",
    "chicken",
    "chief",
    "child",
    "chimney",
    "choice",
    "choose",
    "chunk",
    "cinema",
    "circle",
    "citizen",
    "city",
    "civil",
    "claim",
    "clap",
    "clarify",
    "claw",
    "clay",
    "clean",
    "clever",
    "click",
    "client",
    "cliff",
    "climb",
    "clinic",
    "clip",
    "clock",
    "close",
    "cloth",
    "cloud",
    "clown",
    "club",
    "clump",
    "cluster",
    "clutch",
    "coach",
    "coast",
    "coconut",
    "code",
    "coffee",
    "coil",
    "coin",
    "collect",
    "color",
    "column",
    "combine",
    "come",
    "comfort",
    "comic",
    "common",
    "company",
    "concert",
    "conduct",
    "confirm",
    "congress",
    "connect",
    "consider",
    "control",
    "convince",
    "cook",
    "cool",
    "copper",
    "copy",
    "coral",
    "core",
    "corn",
    "correct",
    "cost",
    "cotton",
    "couch",
    "country",
    "couple",
    "course",
    "cousin",
    "cover",
    "coyote",
    "crack",
    "cradle",
    "craft",
    "cream",
    "credit",
    "creek",
    "crew",
    "cricket",
    "crime",
    "crisp",
    "critic",
    "crop",
    "cross",
    "crouch",
    "crowd",
    "cruel",
    "cruise",
    "crumble",
    "crush",
    "cry",
    "crystal",
    "cube",
    "culture",
    "cup",
    "cupboard",
    "curious",
    "current",
    "curtain",
    "curve",
    "cushion",
    "custom",
    "cute",
    "cycle",
    "dad",
    "damage",
    "damp",
    "dance",
    "danger",
    "daring",
    "dash",
    "daughter",
    "dawn",
    "day",
    "deal",
    "debate",
    "debris",
    "decade",
    "december",
    "decide",
    "decline",
    "decorate",
    "decrease",
    "deer",
    "defense",
    "define",
    "defy",
    "degree",
    "delay",
    "deliver",
    "demand",
    "deny",
    "depart",
    "depend",
    "deposit",
    "depth",
    "deputy",
    "derive",
    "describe",
    "desert",
    "design",
    "desk",
    "despair",
    "destroy",
    "detail",
    "detect",
    "develop",
    "device",
    "devote",
    "diagram",
    "dial",
    "diamond",
    "diary",
    "dice",
    "diesel",
    "diet",
    "differ",
    "digital",
    "dignity",
    "dilemma",
    "dinner",
    "dinosaur",
    "direct",
    "dirt",
    "discover",
    "disease",
    "dish",
    "dismiss",
    "disorder",
    "display",
    "distance",
    "divert",
    "divide",
    "dizzy",
    "doctor",
    "document",
    "dog",
    "doll",
    "dolphin",
    "domain",
    "donate",
    "donkey",
    "donor",
    "door",
    "dose",
    "double",
    "dove",
    "draft",
    "dragon",
    "drama",
    "drastic",
    "draw",
    "dream",
    "dress",
    "drift",
    "drill",
    "drink",
    "drip",
    "drive",
    "drop",
    "drum",
    "dry",
    "duck",
    "dumb",
    "dune",
    "during",
    "dust",
    "dutch",
    "duty",
    "dwarf",
    "dynamic",
    "eager",
    "eagle",
    "early",
    "earn",
    "earth",
    "easily",
    "east",
    "easy",
    "echo",
    "ecology",
    "economy",
    "edge",
    "edit",
    "educate",
    "effort",
    "eight",
    "either",
    "elbow",
    "elder",
    "electric",
    "elegant",
    "element",
    "elephant",
    "elevator",
    "elite",
    "else",
    "embark",
    "embody",
    "embrace",
    "emerge",
    "emotion",
    "employ",
    "empower",
    "empty",
    "enable",
    "end",
    "endless",
    "endorse",
    "enemy",
    "energy",
    "enforce",
    "engage",
    "engine",
    "enjoy",
    "enough",
    "enrich",
    "enroll",
    "ensure",
    "enter",
    "entire",
    "entry",
    "envelope",
    "episode",
    "equal",
    "equip",
    "era",
    "erase",
    "erode",
    "erosion",
    "error",
    "erupt",
    "escape",
    "essay",
    "essence",
    "estate",
    "eternal",
    "ethics",
    "evidence",
    "evil",
    "evolve",
    "exact",
    "example",
    "excess",
    "exchange",
    "excite",
    "exclude",
    "excuse",
    "execute",
    "exercise",
    "exhaust",
    "exhibit",
    "exile",
    "exist",
    "exit",
    "exotic",
    "expand",
    "expect",
    "expire",
    "explain",
    "expose",
    "express",
    "extend",
    "extra",
    "eye",
    "fabric",
    "face",
    "faculty",
    "faint",
    "faith",
    "fall",
    "false",
    "fame",
    "family",
    "famous",
    "fan",
    "fancy",
    "fantasy",
    "farm",
    "fashion",
    "fatal",
    "father",
    "fatigue",
    "fault",
    "favorite",
    "feature",
    "february",
    "federal",
    "fee",
    "feed",
    "feel",
    "female",
    "fence",
    "festival",
    "fetch",
    "fever",
    "few",
    "fiber",
    "fiction",
    "field",
    "figure",
    "file",
    "film",
    "filter",
    "final",
    "find",
    "fine",
    "finger",
    "finish",
    "fire",
    "firm",
    "fiscal",
    "fish",
    "fit",
    "flag",
    "flame",
    "flash",
    "flat",
    "flavor",
    "flee",
    "flight",
    "flip",
    "float",
    "flock",
    "floor",
    "flower",
    "fluid",
    "flush",
    "fly",
    "foam",
    "focus",
    "fog",
    "foil",
    "fold",
    "follow",
    "food",
    "foot",
    "force",
    "forest",
    "forget",
    "fork",
    "fortune",
    "forum",
    "forward",
    "fossil",
    "foster",
    "found",
    "fox",
    "fragile",
    "frame",
    "frequent",
    "fresh",
    "friend",
    "fringe",
    "frog",
    "front",
    "frost",
    "frown",
    "frozen",
    "fruit",
    "fuel",
    "fun",
    "funny",
    "furnace",
    "fury",
    "future",
    "gadget",
    "gain",
    "galaxy",
    "gallery",
    "game",
    "gap",
    "garage",
    "garbage",
    "garden",
    "garlic",
    "garment",
    "gas",
    "gasp",
    "gate",
    "gather",
    "gauge",
    "gaze",
    "general",
    "genius",
    "genre",
    "gentle",
    "genuine",
    "gesture",
    "ghost",
    "giant",
    "gift",
    "giggle",
    "ginger",
    "giraffe",
    "glad",
    "glance",
    "glare",
    "glass",
    "glide",
    "glimpse",
    "globe",
    "gloom",
    "glory",
    "glove",
    "glow",
    "glue",
    "goat",
    "goddess",
    "gold",
    "good",
    "goose",
    "gorilla",
    "gospel",
    "gossip",
    "govern",
    "gown",
    "grab",
    "grace",
    "grain",
    "grant",
    "grape",
    "grass",
    "gravity",
    "great",
    "green",
    "grid",
    "grief",
    "grit",
    "grocery",
    "group",
    "grow",
    "grunt",
    "guard",
    "guess",
    "guide",
    "guilt",
    "guitar",
    "gun",
    "gym",
    "habit",
    "hair",
    "half",
    "hammer",
    "hamster",
    "hand",
    "happy",
    "harbor",
    "hard",
    "harsh",
    "harvest",
    "hat",
    "have",
    "hawk",
    "hazard",
    "head",
    "health",
    "heart",
    "heavy",
    "hedgehog",
    "height",
    "hello",
    "helmet",
    "help",
    "hero",
    "hidden",
    "high",
    "hill",
    "hint",
    "hip",
    "hire",
    "history",
    "hobby",
    "hockey",
    "hold",
    "hole",
    "holiday",
    "hollow",
    "home",
    "honey",
    "hood",
    "hope",
    "horn",
    "horror",
    "horse",
    "hospital",
    "host",
    "hotel",
    "hour",
    "hover",
    "hub",
    "huge",
    "human",
    "humor",
    "hundred",
    "hungry",
    "hunt",
    "hurdle",
    "hurry",
    "hurt",
    "husband",
    "hybrid",
    "ice",
    "icon",
    "idea",
    "identify",
    "idle",
    "ignore",
    "image",
    "imitate",
    "impact",
    "impose",
    "improve",
    "impulse",
    "inch",
    "include",
    "income",
    "increase",
    "index",
    "indicate",
    "indoor",
    "industry",
    "infant",
    "inflict",
    "inform",
    "initial",
    "inject",
    "inmate",
    "inner",
    "innocent",
    "input",
    "inquiry",
    "insane",
    "insect",
    "inside",
    "inspire",
    "install",
    "intact",
    "interest",
    "into",
    "invest",
    "invite",
    "involve",
    "iron",
    "island",
    "isolate",
    "issue",
    "item",
    "ivory",
    "jacket",
    "jaguar",
    "jar",
    "jazz",
    "jealous",
    "jeans",
    "jelly",
    "jewel",
    "job",
    "join",
    "joke",
    "journey",
    "joy",
    "judge",
    "juice",
    "jump",
    "jungle",
    "junior",
    "junk",
    "just",
    "kangaroo",
    "keen",
    "keep",
    "ketchup",
    "key",
    "kick",
    "kid",
    "kidney",
    "kind",
    "kingdom",
    "kiss",
    "kit",
    "kitchen",
    "kite",
    "kitten",
    "kiwi",
    "knee",
    "knife",
    "knock",
    "know",
    "lab",
    "label",
    "labor",
    "ladder",
    "lady",
    "lake",
    "lamp",
    "language",
    "laptop",
    "large",
    "later",
    "latin",
    "laugh",
    "laundry",
    "lava",
    "law",
    "lawn",
    "lawsuit",
    "layer",
    "lazy",
    "leader",
    "leaf",
    "learn",
    "leave",
    "lecture",
    "left",
    "leg",
    "legal",
    "legend",
    "leisure",
    "lemon",
    "lend",
    "length",
    "lens",
    "leopard",
    "lesson",
    "letter",
    "level",
    "liberty",
    "library",
    "license",
    "life",
    "light",
    "like",
    "limb",
    "limit",
    "link",
    "lion",
    "liquid",
    "list",
    "little",
    "live",
    "lizard",
    "load",
    "loan",
    "lobster",
    "local",
    "lock",
    "logic",
    "lonely",
    "long",
    "loop",
    "lottery",
    "loud",
    "lounge",
    "love",
    "loyal",
    "lucky",
    "luggage",
    "lumber",
    "lunar",
    "lunch",
    "luxury",
    "lyrics",
    "machine",
    "mad",
    "magic",
    "magnet",
    "maid",
    "mail",
    "main",
    "major",
    "make",
    "mammal",
    "man",
    "manage",
    "mandate",
    "mango",
    "mansion",
    "manual",
    "maple",
    "marble",
    "march",
    "margin",
    "marine",
    "market",
    "marriage",
    "mask",
    "mass",
    "master",
    "match",
    "material",
    "math",
    "matrix",
    "matter",
    "maximum",
    "maze",
    "meadow",
    "mean",
    "measure",
    "meat",
    "mechanic",
    "medal",
    "media",
    "melody",
    "melt",
    "member",
    "memory",
    "mention",
    "menu",
    "mercy",
    "merge",
    "merit",
    "mesh",
    "metal",
    "method",
    "middle",
    "midnight",
    "milk",
    "million",
    "mimic",
    "mind",
    "minimum",
    "minor",
    "minute",
    "miracle",
    "mirror",
    "misery",
    "miss",
    "mistake",
    "mix",
    "mixed",
    "mixture",
    "mobile",
    "model",
    "modify",
    "mom",
    "moment",
    "monitor",
    "monkey",
    "monster",
    "month",
    "moon",
    "moral",
    "more",
    "morning",
    "mosquito",
    "mother",
    "motion",
    "motor",
    "mountain",
    "mouse",
    "move",
    "movie",
    "much",
    "muffin",
    "mule",
    "multiply",
    "muscle",
    "museum",
    "music",
    "must",
    "mutual",
    "myself",
    "mystery",
    "myth",
    "naive",
    "name",
    "napkin",
    "narrow",
    "nasty",
    "nation",
    "nature",
    "near",
    "neck",
    "need",
    "negative",
    "neglect",
    "neither",
    "nephew",
    "nerve",
    "nest",
    "net",
    "network",
    "neutral",
    "never",
    "news",
    "next",
    "nice",
    "night",
    "noble",
    "noise",
    "nominee",
    "normal",
    "north",
    "nose",
    "notable",
    "nothing",
    "notice",
    "novel",
    "now",
    "nuclear",
    "number",
    "nurse",
    "nut",
    "oak",
    "obey",
    "object",
    "obtain",
    "obvious",
    "occur",
    "ocean",
  ];

  function passphrase(wordCount, separator) {
    wordCount = wordCount || 4;
    separator = separator || "-";
    var bytes = randomBytes(wordCount * 2); // 2 bytes per word for better distribution
    var words = [];
    for (var i = 0; i < wordCount; i++) {
      var index = ((bytes[i * 2] << 8) | bytes[i * 2 + 1]) % WORDS.length;
      words.push(WORDS[index]);
    }
    return words.join(separator);
  }

  // --- Generator definitions ---
  var GENERATORS = {
    memorable: {
      label: "Memorable Passphrase",
      fn: function () {
        return passphrase(4, "-");
      },
      count: 4,
    },
    pin: {
      label: "PIN Code (6 digits)",
      fn: function () {
        return randomFromCharset(CHARSETS.digits, 6);
      },
      count: 4,
    },
    strong16: {
      label: "Strong (16 char)",
      fn: function () {
        return randomFromCharset(CHARSETS.full, 16);
      },
      count: 4,
    },
    fort32: {
      label: "Fort Knox (32 char)",
      fn: function () {
        return randomFromCharset(CHARSETS.full, 32);
      },
      count: 4,
    },
    alphanum24: {
      label: "Alphanumeric (24)",
      fn: function () {
        return randomFromCharset(CHARSETS.alphanum, 24);
      },
      count: 4,
    },
    hex128: {
      label: "128-bit Hex",
      fn: function () {
        return randomHex(16);
      },
      count: 4,
    },
    hex256: {
      label: "256-bit Hex",
      fn: function () {
        return randomHex(32);
      },
      count: 3,
    },
    base64: {
      label: "Base64 Secret (32B)",
      fn: function () {
        return randomBase64(32);
      },
      count: 3,
    },
    uuid: {
      label: "UUID v4",
      fn: function () {
        return uuidV4();
      },
      count: 4,
    },
    api: {
      label: "API Key Style",
      fn: function () {
        return "sk_live_" + randomFromCharset(CHARSETS.alphanum, 32);
      },
      count: 3,
    },
  };

  // --- Rendering ---
  function generateAll() {
    var container = document.getElementById("keygen-output");
    if (!container) return;
    container.innerHTML = "";

    var order = [
      "memorable",
      "pin",
      "strong16",
      "fort32",
      "alphanum24",
      "hex128",
      "hex256",
      "base64",
      "uuid",
      "api",
    ];
    for (var k = 0; k < order.length; k++) {
      var key = order[k];
      var gen = GENERATORS[key];
      var section = document.createElement("div");
      section.className = "box mb-4";

      var heading = document.createElement("h4");
      heading.className = "title is-5 mb-3";
      heading.textContent = gen.label;
      section.appendChild(heading);

      for (var i = 0; i < gen.count; i++) {
        var value = gen.fn();
        var row = document.createElement("div");
        row.className = "field has-addons mb-2";

        var inputControl = document.createElement("div");
        inputControl.className = "control is-expanded";
        var input = document.createElement("input");
        input.className = "input is-family-monospace is-small";
        input.type = "text";
        input.readOnly = true;
        input.value = value;
        inputControl.appendChild(input);
        row.appendChild(inputControl);

        var btnControl = document.createElement("div");
        btnControl.className = "control";
        var btn = document.createElement("button");
        btn.className = "button is-info is-small";
        btn.innerHTML = '<span class="icon"><i class="fas fa-copy"></i></span>';
        btn.title = "Copy to clipboard";
        btn.setAttribute("data-value", value);
        btn.addEventListener("click", copyHandler);
        btnControl.appendChild(btn);
        row.appendChild(btnControl);

        section.appendChild(row);
      }
      container.appendChild(section);
    }
  }

  function copyHandler(e) {
    var btn = e.currentTarget;
    var value = btn.getAttribute("data-value");
    navigator.clipboard.writeText(value).then(function () {
      btn.innerHTML = '<span class="icon"><i class="fas fa-check"></i></span>';
      btn.classList.remove("is-info");
      btn.classList.add("is-success");
      setTimeout(function () {
        btn.innerHTML = '<span class="icon"><i class="fas fa-copy"></i></span>';
        btn.classList.remove("is-success");
        btn.classList.add("is-info");
      }, 1500);
    });
  }

  // --- Init ---
  document.addEventListener("DOMContentLoaded", function () {
    // Generate on load
    generateAll();

    // Regenerate button
    var regenBtn = document.getElementById("keygen-regenerate");
    if (regenBtn) {
      // Hint for keyboard shortcut
      var hint = document.createElement("p");
      hint.className = "help is-size-7";
      hint.textContent = "Tip: Press R to regenerate all keys.";
      regenBtn.insertAdjacentElement("afterend", hint);

      regenBtn.addEventListener("click", generateAll);
    }

    // Keyboard shortcut: R to regenerate
    document.addEventListener("keydown", function (e) {
      if (e.key === "r" || e.key === "R") {
        // Don't trigger if user is typing in an input
        if (e.target.tagName === "INPUT" || e.target.tagName === "TEXTAREA")
          return;
        generateAll();
      }
    });
  });
})();
